Log iniciado em 2024-11-29 15:50:42

Todos os prints, erros e logs estão sendo gravados em: C:\Users\igorg\PycharmProjects\beepIA\logsAI\log_2024-11-29_15-50-42.txt

Traceback (most recent call last):
  File "C:\Users\igorg\PycharmProjects\beepIA\AppIA.py", line 33, in <module>
    from router import router
  File "C:\Users\igorg\PycharmProjects\beepIA\router\__init__.py", line 1, in <module>
    from .router import router
  File "C:\Users\igorg\PycharmProjects\beepIA\router\router.py", line 8, in <module>
    from AppIA import Logger, log_file
  File "C:\Users\igorg\PycharmProjects\beepIA\AppIA.py", line 38, in <module>
    app.include_router(router)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "C:\Users\igorg\PycharmProjects\beepIA\.venv\Lib\site-packages\fastapi\applications.py", line 1447, in include_router
    self.router.include_router(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^
        router,
        ^^^^^^^
    ...<8 lines>...
        generate_unique_id_function=generate_unique_id_function,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\igorg\PycharmProjects\beepIA\.venv\Lib\site-packages\fastapi\routing.py", line 1263, in include_router
    for r in router.routes:
             ^^^^^^^^^^^^^
AttributeError: partially initialized module 'router.router' from 'C:\Users\igorg\PycharmProjects\beepIA\router\router.py' has no attribute 'routes' (most likely due to a circular import)
Traceback (most recent call last):
  File "C:\Users\igorg\PycharmProjects\beepIA\AppIA.py", line 33, in <module>
    from router import router
  File "C:\Users\igorg\PycharmProjects\beepIA\router\__init__.py", line 1, in <module>
    from .router import router
  File "C:\Users\igorg\PycharmProjects\beepIA\router\router.py", line 8, in <module>
    from AppIA import Logger, log_file
  File "C:\Users\igorg\PycharmProjects\beepIA\AppIA.py", line 38, in <module>
    app.include_router(router)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "C:\Users\igorg\PycharmProjects\beepIA\.venv\Lib\site-packages\fastapi\applications.py", line 1447, in include_router
    self.router.include_router(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^
        router,
        ^^^^^^^
    ...<8 lines>...
        generate_unique_id_function=generate_unique_id_function,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\igorg\PycharmProjects\beepIA\.venv\Lib\site-packages\fastapi\routing.py", line 1263, in include_router
    for r in router.routes:
             ^^^^^^^^^^^^^
AttributeError: partially initialized module 'router.router' from 'C:\Users\igorg\PycharmProjects\beepIA\router\router.py' has no attribute 'routes' (most likely due to a circular import)
